package com.unified.provisioning.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-31T09:34:53.165+07:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "ProvisioningServiceImplService", 
                  wsdlLocation = "http://10.8.37.13:8080/soap_prov/ProvisioningService?wsdl",
                  targetNamespace = "http://ws.provisioning.unified.com/") 
public class ProvisioningServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.provisioning.unified.com/", "ProvisioningServiceImplService");
    public final static QName ProvisioningServiceImplPort = new QName("http://ws.provisioning.unified.com/", "ProvisioningServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.8.37.13:8080/soap_prov/ProvisioningService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProvisioningServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.8.37.13:8080/soap_prov/ProvisioningService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProvisioningServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProvisioningServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvisioningServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProvisioningService
     */
    @WebEndpoint(name = "ProvisioningServiceImplPort")
    public ProvisioningService getProvisioningServiceImplPort() {
        return super.getPort(ProvisioningServiceImplPort, ProvisioningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvisioningService
     */
    @WebEndpoint(name = "ProvisioningServiceImplPort")
    public ProvisioningService getProvisioningServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProvisioningServiceImplPort, ProvisioningService.class, features);
    }

}
