
package com.unified.provisioning.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-31T09:34:53.087+07:00
 * Generated source version: 2.6.1
 * 
 */
public final class ProvisioningService_ProvisioningServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.provisioning.unified.com/", "ProvisioningServiceImplService");

    private ProvisioningService_ProvisioningServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProvisioningServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProvisioningServiceImplService ss = new ProvisioningServiceImplService(wsdlURL, SERVICE_NAME);
        ProvisioningService port = ss.getProvisioningServiceImplPort();  
        
        {
        System.out.println("Invoking activate...");
        com.unified.provisioning.ws.RequestHeader _activate_header = new com.unified.provisioning.ws.RequestHeader();
        _activate_header.setAccessMedia("AccessMedia1613831050");
        _activate_header.setExternalId("ExternalId-456955777");
        _activate_header.setMsisdn("Msisdn1019409239");
        java.lang.String _activate_serviceName = "_activate_serviceName-1655499323";
        com.unified.provisioning.ws.Response _activate__return = port.activate(_activate_header, _activate_serviceName);
        System.out.println("activate.result=" + _activate__return);


        }
        {
        System.out.println("Invoking subscribe...");
        com.unified.provisioning.ws.RequestHeader _subscribe_header = new com.unified.provisioning.ws.RequestHeader();
        _subscribe_header.setAccessMedia("AccessMedia-259070020");
        _subscribe_header.setExternalId("ExternalId-169133775");
        _subscribe_header.setMsisdn("Msisdn-1780963958");
        java.lang.String _subscribe_imsi = "_subscribe_imsi1096556397";
        int _subscribe_subscriberType = 2087350519;
        int _subscribe_packageType = 1425031540;
        java.lang.String _subscribe_serviceName = "_subscribe_serviceName559937102";
        com.unified.provisioning.ws.Response _subscribe__return = port.subscribe(_subscribe_header, _subscribe_imsi, _subscribe_subscriberType, _subscribe_packageType, _subscribe_serviceName);
        System.out.println("subscribe.result=" + _subscribe__return);


        }
        {
        System.out.println("Invoking terminate...");
        com.unified.provisioning.ws.RequestHeader _terminate_header = new com.unified.provisioning.ws.RequestHeader();
        _terminate_header.setAccessMedia("AccessMedia-709429724");
        _terminate_header.setExternalId("ExternalId761864489");
        _terminate_header.setMsisdn("Msisdn-2037186141");
        java.lang.String _terminate_serviceName = "_terminate_serviceName2053647251";
        com.unified.provisioning.ws.Response _terminate__return = port.terminate(_terminate_header, _terminate_serviceName);
        System.out.println("terminate.result=" + _terminate__return);


        }
        {
        System.out.println("Invoking renewalFailure...");
        com.unified.provisioning.ws.RequestHeader _renewalFailure_header = new com.unified.provisioning.ws.RequestHeader();
        _renewalFailure_header.setAccessMedia("AccessMedia-1347860100");
        _renewalFailure_header.setExternalId("ExternalId-1870035462");
        _renewalFailure_header.setMsisdn("Msisdn-1995582818");
        int _renewalFailure_renewalStatus = -1263707663;
        java.lang.String _renewalFailure_serviceName = "_renewalFailure_serviceName1363138205";
        com.unified.provisioning.ws.Response _renewalFailure__return = port.renewalFailure(_renewalFailure_header, _renewalFailure_renewalStatus, _renewalFailure_serviceName);
        System.out.println("renewalFailure.result=" + _renewalFailure__return);


        }
        {
        System.out.println("Invoking switchBillType...");
        com.unified.provisioning.ws.RequestHeader _switchBillType_header = new com.unified.provisioning.ws.RequestHeader();
        _switchBillType_header.setAccessMedia("AccessMedia-231371525");
        _switchBillType_header.setExternalId("ExternalId31408113");
        _switchBillType_header.setMsisdn("Msisdn-101900802");
        int _switchBillType_subscriberType = 911395072;
        int _switchBillType_packageType = -994062566;
        java.lang.String _switchBillType_serviceName = "_switchBillType_serviceName-1713545163";
        com.unified.provisioning.ws.Response _switchBillType__return = port.switchBillType(_switchBillType_header, _switchBillType_subscriberType, _switchBillType_packageType, _switchBillType_serviceName);
        System.out.println("switchBillType.result=" + _switchBillType__return);


        }
        {
        System.out.println("Invoking recycle...");
        com.unified.provisioning.ws.RequestHeader _recycle_header = new com.unified.provisioning.ws.RequestHeader();
        _recycle_header.setAccessMedia("AccessMedia1404901092");
        _recycle_header.setExternalId("ExternalId-815209609");
        _recycle_header.setMsisdn("Msisdn-777674914");
        java.lang.String _recycle_serviceName = "_recycle_serviceName-176435274";
        com.unified.provisioning.ws.Response _recycle__return = port.recycle(_recycle_header, _recycle_serviceName);
        System.out.println("recycle.result=" + _recycle__return);


        }

        System.exit(0);
    }

}
