package com.unified.provisioning.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-31T09:34:53.149+07:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.provisioning.unified.com/", name = "ProvisioningService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ProvisioningService {

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response activate(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response subscribe(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "imsi", name = "imsi")
        java.lang.String imsi,
        @WebParam(partName = "subscriberType", name = "subscriberType")
        int subscriberType,
        @WebParam(partName = "packageType", name = "packageType")
        int packageType,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response terminate(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response renewalFailure(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "renewalStatus", name = "renewalStatus")
        int renewalStatus,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response switchBillType(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "subscriberType", name = "subscriberType")
        int subscriberType,
        @WebParam(partName = "packageType", name = "packageType")
        int packageType,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );

    @WebResult(name = "response", targetNamespace = "http://ws.provisioning.unified.com/", partName = "response")
    @WebMethod
    public Response recycle(
        @WebParam(partName = "header", name = "header")
        RequestHeader header,
        @WebParam(partName = "serviceName", name = "serviceName")
        java.lang.String serviceName
    );
}
