
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.unified.provisioning.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-31T09:34:53.134+07:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProvisioningServiceImplService",
                      portName = "ProvisioningServiceImplPort",
                      targetNamespace = "http://ws.provisioning.unified.com/",
                      wsdlLocation = "http://10.8.37.13:8080/soap_prov/ProvisioningService?wsdl",
                      endpointInterface = "com.unified.provisioning.ws.ProvisioningService")
                      
public class ProvisioningServiceImpl implements ProvisioningService {

    private static final Logger LOG = Logger.getLogger(ProvisioningServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#activate(com.unified.provisioning.ws.RequestHeader  header ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response activate(RequestHeader header,java.lang.String serviceName) { 
        LOG.info("Executing operation activate");
        System.out.println(header);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(-2018118099);
            _return.setResponseDescription("ResponseDescription1605743984");
            _return.setResponseName("ResponseName894881999");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#subscribe(com.unified.provisioning.ws.RequestHeader  header ,)java.lang.String  imsi ,)int  subscriberType ,)int  packageType ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response subscribe(RequestHeader header,java.lang.String imsi,int subscriberType,int packageType,java.lang.String serviceName) { 
        LOG.info("Executing operation subscribe");
        System.out.println(header);
        System.out.println(imsi);
        System.out.println(subscriberType);
        System.out.println(packageType);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(2040803669);
            _return.setResponseDescription("ResponseDescription-174114592");
            _return.setResponseName("ResponseName-730898311");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#terminate(com.unified.provisioning.ws.RequestHeader  header ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response terminate(RequestHeader header,java.lang.String serviceName) { 
        LOG.info("Executing operation terminate");
        System.out.println(header);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(-1411422283);
            _return.setResponseDescription("ResponseDescription-652518992");
            _return.setResponseName("ResponseName-1384849966");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#renewalFailure(com.unified.provisioning.ws.RequestHeader  header ,)int  renewalStatus ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response renewalFailure(RequestHeader header,int renewalStatus,java.lang.String serviceName) { 
        LOG.info("Executing operation renewalFailure");
        System.out.println(header);
        System.out.println(renewalStatus);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(880587270);
            _return.setResponseDescription("ResponseDescription1105111557");
            _return.setResponseName("ResponseName694913151");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#switchBillType(com.unified.provisioning.ws.RequestHeader  header ,)int  subscriberType ,)int  packageType ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response switchBillType(RequestHeader header,int subscriberType,int packageType,java.lang.String serviceName) { 
        LOG.info("Executing operation switchBillType");
        System.out.println(header);
        System.out.println(subscriberType);
        System.out.println(packageType);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(1726065973);
            _return.setResponseDescription("ResponseDescription809801074");
            _return.setResponseName("ResponseName-2080750824");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.unified.provisioning.ws.ProvisioningService#recycle(com.unified.provisioning.ws.RequestHeader  header ,)java.lang.String  serviceName )*
     */
    public com.unified.provisioning.ws.Response recycle(RequestHeader header,java.lang.String serviceName) { 
        LOG.info("Executing operation recycle");
        System.out.println(header);
        System.out.println(serviceName);
        try {
            com.unified.provisioning.ws.Response _return = new com.unified.provisioning.ws.Response();
            _return.setResponseCode(-1964092351);
            _return.setResponseDescription("ResponseDescription1784538484");
            _return.setResponseName("ResponseName510927427");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
