/**
 * IpChargingSession.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.2.1 Aug 08, 2005 (11:49:10 PDT) WSDL2Java emitter.
 */

package org.csapi.www.cs.wsdl;

public interface IpChargingSession extends java.rmi.Remote {
    public void setCallback(java.lang.String appInterface) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_INTERFACE_TYPE, org.csapi.www.osa.wsdl.TpCommonExceptions;
    public void setCallbackWithSessionID(java.lang.String appInterface, int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_INTERFACE_TYPE, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void creditAmountReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingPrice amount, boolean closeReservation, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_AMOUNT, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID, org.csapi.www.osa.wsdl.P_INVALID_CURRENCY;
    public void creditUnitReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpVolumeSet volumes, boolean closeReservation, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_VOLUME, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void debitAmountReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingPrice amount, boolean closeReservation, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_AMOUNT, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID, org.csapi.www.osa.wsdl.P_INVALID_CURRENCY;
    public void debitUnitReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpVolumeSet volumes, boolean closeReservation, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_VOLUME, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void directCreditAmountReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpChargingPrice amount, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_AMOUNT, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID, org.csapi.www.osa.wsdl.P_INVALID_CURRENCY;
    public void directCreditUnitReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpVolumeSet volumes, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_VOLUME, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void directDebitAmountReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpChargingPrice amount, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_AMOUNT, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID, org.csapi.www.osa.wsdl.P_INVALID_CURRENCY;
    public void directDebitUnitReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpVolumeSet volumes, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_VOLUME, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void extendLifeTimeReq(int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public org.csapi.www.cs.schema.TpChargingPrice getAmountLeft(int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public int getLifeTimeLeft(int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public org.csapi.www.cs.schema.TpVolumeSet getUnitLeft(int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void rateReq(int sessionID, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void release(int sessionID, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public void reserveAmountReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpChargingPrice preferredAmount, org.csapi.www.cs.schema.TpChargingPrice minimumAmount, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.P_INVALID_AMOUNT, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID, org.csapi.www.osa.wsdl.P_INVALID_CURRENCY;
    public void reserveUnitReq(int sessionID, org.csapi.www.cs.schema.TpApplicationDescription applicationDescription, org.csapi.www.cs.schema.TpChargingParameterSet chargingParameters, org.csapi.www.cs.schema.TpVolumeSet volumes, int requestNumber) throws java.rmi.RemoteException, org.csapi.www.cs.wsdl.P_INVALID_VOLUME, org.csapi.www.cs.wsdl.P_INVALID_REQUEST_NUMBER, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
    public int cmvtGetClassOfService(int sessionID) throws java.rmi.RemoteException, org.csapi.www.osa.wsdl.TpCommonExceptions, org.csapi.www.osa.wsdl.P_INVALID_SESSION_ID;
}
